package com.codelamps.belajarspring.belajarspring;

import org.springframework.context.annotation.Configuration;

/** MEMBUAT KELAS UNTUK CONFIGURATION
 ANNOTATION CONFIGURATION DIGUNAKAN UNTUK MEMBUAT APPLICATION CONTEXT MENGGUNAKAN ANNOTATION
 KETIKA KITA INGIN MEMBUAT APPLICATION CONTEXT MENGGUNAKAN ANNOTATION, KITA PERLU MEMBUAT CONFIGURATION CLASS
 CONFIGURATION CLASS ADALAH SEBUAH CLASS YANG TERDAPAT ANNOTATION @CONFIGURATION PADA CLASS TERSEBUT
**/
@Configuration
public class ApplicationConfiguration {
}
